server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  profiles:
    active: dev

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG