version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_course
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ead_course_two
      MYSQL_PASSWORD: root
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
