name: Java CI with Maven

on:
  push:
    branches:
      - 'feature/*'
      - 'develop'
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ead_course_test
          MYSQL_USER: user
          MYSQL_PASSWORD: root
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --port=3307 --user=user --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MySQL
        run: |
          while ! docker exec mysql mysqladmin --user=user --password=root --host "127.0.0.1" --port "3307" ping --silent; do
            sleep 10
          done

      - name: Run Unit and Integration Tests
        run: mvn test verify -DskipTests=false --file pom.xml

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install --file pom.xml
