name: Java CI with Maven

on:
  push:
    branches:
      - 'feature/*'
      - 'develop'
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Start Services
      run: docker-compose -f ./src/docker/docker-compose.yml up -d

    - name: Check Services Health
      run: |
        check_service() {
          service_name=$1
          port=$2
          echo "Waiting for $service_name to launch on $port..."
          timeout=180 # Timeout after 3 minutes
          while ! nc -z localhost $port; do
            sleep 10
            timeout=$((timeout-10))
            if [ $timeout -le 0 ]; then
              echo "$service_name failed to start, printing logs:"
              docker-compose logs $service_name
              exit 1
            fi
          done
          echo "$service_name launched"
        }

        check_service eureka-server 8761
        check_service api-gateway 8080

    - name: Run Unit and Integration Tests
      run: mvn test verify -DskipTests=false --file pom.xml

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build and Check for Build Failures
      run: |
        mvn clean install --file pom.xml || (echo "Build failed, printing logs for services:" && docker-compose logs && exit 1)
