name: Java CI with Maven

on:
  push:
    branches:
      - 'feature/*'
      - 'develop'
      - 'main'
      
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Start Services
      run: docker-compose -f ./src/docker/docker-compose.yml up -d

    - name: Print Eureka Server logs if it fails to start
      run: |
        echo "Waiting for Eureka Server to launch on 8761..."
        timeout=90 # Timeout after 90 seconds
        while ! nc -z localhost 8761; do
          sleep 10
          timeout=$((timeout-10))
          if [ $timeout -le 0 ]; then
            echo "Eureka Server failed to start, printing logs:"
            docker-compose logs eureka-server
            exit 1
          fi
        done
        echo "Eureka Server launched"
    
    - name: Wait for API Gateway
      run: |
        echo "Waiting for API Gateway to launch on 8080..."
        timeout=90 # Timeout after 90 seconds
        while ! nc -z localhost 8080; do
          sleep 10
          timeout=$((timeout-10))
          if [ $timeout -le 0 ]; then
            echo "API Gateway failed to start, printing logs:"
            docker-compose logs api-gateway
            exit 1
          fi
        done
        echo "API Gateway launched"
    
    - name: Run Unit and Integration Tests
      run: mvn test verify -DskipTests=false --file pom.xml

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build
      run: mvn clean install --file pom.xml
